warnings_are_errors: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
dist: trusty
script:
  - npm test
  - CI=false npm run build
notifications:
  email:
    on_success: change
    on_failure: change
